version: '4.1'

services:
  api:
    build:
      context: ./power-pay-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  frontend:
    build:
      context: ./power-pay-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:3000

  translator:
    build:
      context: ./power-pay-translator
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - BACKEND_API_URL=http://api:8080

volumes:
  postgres: { }