version: '4.1'

services:
  api:
    build:
      context: ./power-pay-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/postgres"
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data

  frontend:
    build:
      context: ./power-pay-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_BACKEND_URL=http://api:8080

  translator:
    build:
      context: ./power-pay-translator
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - BACKEND_API_URL=http://api:8080

volumes:
  postgres: { }