spring:
  application:
    name: e2e-banking-app

  datasource:
    url: jdbc:postgresql://localhost:5432/bank1
    username: e2e
    password: e2e1234.
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: always
