name: Build Backend

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
    paths:
      - 'power-pay-backend/**'
      - '.github/workflows/build-service.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-backend


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: power-pay-backend

    steps:
      - name: Clone the project
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Maven build
        run: mvn clean package -q
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: power-pay-backend
          path: power-pay-backend/target/*.jar

  docker-build:
    needs:
      - build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: power-pay-backend

    permissions:
      contents: read
      packages: write

    steps:
      - name: Clone the project
        uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: power-pay-backend
          path: power-pay-backend/target

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: lowercase_name
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_NAME}}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.lowercase_name.outputs.lowercase }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./power-pay-backend
          push: "${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}"
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      
