name: Build Backend

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
    paths:
      - 'power-pay-backend/**'
      - '.github/workflows/build-service.yml'

  pull_request:
    branches:
      - '**'
    paths:
      - 'power-pay-backend/**'
      - '.github/workflows/build-service.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}-backend


jobs:
  build:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Maven build
        run: cd power-pay-backend && mvn clean package -q
      
  docker-build:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
          
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: lowercase_name
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ env.IMAGE_NAME}}
          
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ steps.lowercase_name.outputs.lowercase }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        if: github.event_name != 'pull_request'
        with:
          context: ./power-pay-backend
          file: ./power-pay-backend/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      
      
