name: Build Backend

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - '**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Backend
        run: cd power-pay-backend && mvn package

      - id: string
        uses: ASzc/change-string-case-action@v6
        with:
          string: github.repository
      - id: Output_Lowercase_String
        run: echo ${{ steps.string.outputs.lowercase }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./power-pay-backend
          file: ./power-pay-backend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
      
      