name: Build NodeJS

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - '**'
permissions:
  contents: read
  packages: write
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Npm install
        run: cd power-pay-frontend && npm ci

      - name: Login to the Docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Frontend
        run: cd power-pay-frontend && npm run build

      - id: string
        uses: AsZc/change-string-case-action@v6
        with:
          string: ${{github.repository}}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./power-pay-frontend
          file: ./power-pay-frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.string.outputs.lowercase }}:latest
      