name: Build NodeJS

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Npm install
        run: cd power-pay-frontend && npm ci
      - name: Build Frontend
        run: cd power-pay-frontend && npm run build