name: Build NodeJS

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Npm install
        run: cd power-pay-frontend && npm ci

      - name: Login to the Docker registry
        uses: docker/login-action@v2
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./power-pay-frontend
          file: ./power-pay-frontend/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
      - name: Build Frontend
        run: cd power-pay-frontend && npm run build