name: Build Translator

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build Translator
        run: cd power-pay-translator && cargo build --verbose && cargo test --verbose

      - name: Login to the Docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: String
        uses: AsZc/change-string-case-action@v6
        with: 
          string: ${{ github.repository }}

      - name: Enable create organization packages
        run: |
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          -X POST \
          https://api.github.com/orgs/${{ github.repository_owner }}/actions/permissions/orgs \
          -d '{"permission": "write"}'

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./power-pay-translator
          file: ./power-pay-translator/Dockerfile
          push: true
          tags: ghcr.io/${{ steps.string.outputs.lowercase }}:latest