name: Build Translator

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'
  pull_request:
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Go into Translator
        run: cd power-pay-translator
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose